import {
  DollarSign,
  Utensils,
  ShoppingCart,
  ShoppingBag,
  Car,
  Plane,
  Receipt,
  Home,
  Film,
  HeartPulse,
  Sparkles,
  Wrench,
  Banknote,
  Landmark,
  ArrowLeftRight,
  CircleHelp,
  Target,
  PiggyBank,
  TrendingUp,
  Wallet,
  CreditCard,
  Building2,
  Bitcoin,
  ChartPie,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

// String name -> lucide component. Category `icon` fields index into this.
export const ICONS: Record<string, LucideIcon> = {
  DollarSign,
  Utensils,
  ShoppingCart,
  ShoppingBag,
  Car,
  Plane,
  Receipt,
  Home,
  Film,
  HeartPulse,
  Sparkles,
  Wrench,
  Banknote,
  Landmark,
  ArrowLeftRight,
  CircleHelp,
  Target,
  PiggyBank,
  TrendingUp,
  Wallet,
  CreditCard,
  Building2,
  Bitcoin,
  ChartPie,
  Briefcase,
};

export function getIcon(name?: string | null): LucideIcon {
  return (name && ICONS[name]) || CircleHelp;
}
